
$background = rgba(f6fafeff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(edf1f5ff)

$inverse_primary = rgba(8dcff1ff)

$inverse_surface = rgba(2c3134ff)

$on_background = rgba(171c1fff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(001e2bff)

$on_primary_fixed = rgba(001e2bff)

$on_primary_fixed_variant = rgba(004d66ff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(091e27ff)

$on_secondary_fixed = rgba(091e27ff)

$on_secondary_fixed_variant = rgba(364954ff)

$on_surface = rgba(171c1fff)

$on_surface_variant = rgba(40484cff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(1b1736ff)

$on_tertiary_fixed = rgba(1b1736ff)

$on_tertiary_fixed_variant = rgba(464364ff)

$outline = rgba(71787dff)

$outline_variant = rgba(c0c7cdff)

$primary = rgba(166683ff)

$primary_container = rgba(c0e8ffff)

$primary_fixed = rgba(c0e8ffff)

$primary_fixed_dim = rgba(8dcff1ff)

$scrim = rgba(000000ff)

$secondary = rgba(4d616cff)

$secondary_container = rgba(d0e6f3ff)

$secondary_fixed = rgba(d0e6f3ff)

$secondary_fixed_dim = rgba(b4cad6ff)

$shadow = rgba(000000ff)

$source_color = rgba(16262eff)

$surface = rgba(f6fafeff)

$surface_bright = rgba(f6fafeff)

$surface_container = rgba(eaeef2ff)

$surface_container_high = rgba(e4e9ecff)

$surface_container_highest = rgba(dfe3e7ff)

$surface_container_low = rgba(f0f4f8ff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(d6dadeff)

$surface_tint = rgba(166683ff)

$surface_variant = rgba(dce3e9ff)

$tertiary = rgba(5e5a7dff)

$tertiary_container = rgba(e4dfffff)

$tertiary_fixed = rgba(e4dfffff)

$tertiary_fixed_dim = rgba(c7c2eaff)


