
$background = rgba(fff8f4ff)

$error = rgba(ba1a1aff)

$error_container = rgba(ffdad6ff)

$inverse_on_surface = rgba(fcefe2ff)

$inverse_primary = rgba(f5bc6fff)

$inverse_surface = rgba(362f27ff)

$on_background = rgba(211b13ff)

$on_error = rgba(ffffffff)

$on_error_container = rgba(410002ff)

$on_primary = rgba(ffffffff)

$on_primary_container = rgba(291800ff)

$on_primary_fixed = rgba(291800ff)

$on_primary_fixed_variant = rgba(633f00ff)

$on_secondary = rgba(ffffffff)

$on_secondary_container = rgba(271904ff)

$on_secondary_fixed = rgba(271904ff)

$on_secondary_fixed_variant = rgba(56432bff)

$on_surface = rgba(211b13ff)

$on_surface_variant = rgba(4f4539ff)

$on_tertiary = rgba(ffffffff)

$on_tertiary_container = rgba(101f03ff)

$on_tertiary_fixed = rgba(101f03ff)

$on_tertiary_fixed_variant = rgba(3b4c29ff)

$outline = rgba(817567ff)

$outline_variant = rgba(d3c4b4ff)

$primary = rgba(805611ff)

$primary_container = rgba(ffddb4ff)

$primary_fixed = rgba(ffddb4ff)

$primary_fixed_dim = rgba(f5bc6fff)

$scrim = rgba(000000ff)

$secondary = rgba(705b40ff)

$secondary_container = rgba(fbdebcff)

$secondary_fixed = rgba(fbdebcff)

$secondary_fixed_dim = rgba(dec2a1ff)

$shadow = rgba(000000ff)

$source_color = rgba(ec9d07ff)

$surface = rgba(fff8f4ff)

$surface_bright = rgba(fff8f4ff)

$surface_container = rgba(f9ecdfff)

$surface_container_high = rgba(f3e6daff)

$surface_container_highest = rgba(ede0d4ff)

$surface_container_low = rgba(fff1e5ff)

$surface_container_lowest = rgba(ffffffff)

$surface_dim = rgba(e4d8ccff)

$surface_tint = rgba(805611ff)

$surface_variant = rgba(f0e0d0ff)

$tertiary = rgba(52643fff)

$tertiary_container = rgba(d4eabbff)

$tertiary_fixed = rgba(d4eabbff)

$tertiary_fixed_dim = rgba(b9cda0ff)


