# -----------------------------------------------------
# General window decoration
# name: "Rounding All Blur No Shadows"
# -----------------------------------------------------

decoration {
    rounding = 10
    active_opacity = 0.92
    inactive_opacity = 0.9
    fullscreen_opacity = 1.0

    blur {
      enabled = true
           new_optimizations = true
           size = 8
           passes = 3
           brightness = 2
           contrast = 2
           vibrancy = 2
    }

    shadow {
        enabled = true
        range = 4
        render_power = 3
        color = rgba(1a1a1aee)
    }
}

layerrule {
    name = waybar_blur
    match:namespace = waybar
    blur = true
}

layerrule {
    name = kitty_blur
    match:namespace = kitty
    blur = true
}

layerrule {
    name = swaync_blur
    match:namespace = swaync-notification-window
    blur = true
    ignore_alpha = 0.3
}

layerrule {
    name = swaync_control_blur
    match:namespace = swaync-control-center
    blur = true
    ignore_alpha = 0.3
}
