# -----------------------------------------------------
# Window rules
# -----------------------------------------------------
# Tiling windows (windows tile by default, these rules removed)

# Floating windows
windowrulev = float, title:^(pavucontrol)$
windowrulev = float, title:^(blueman-manager)$
windowrulev = float, title:^(nm-connection-editor)$
windowrulev = float, title:^(qalculate-gtk)$

# Browser Picture in Picture
windowrulev = float, title:^(Picture-in-Picture)$
windowrulev = pin, title:^(Picture-in-Picture)$
windowrulev = move 69.5% 4%, title:^(Picture-in-Picture)$

# idleinhibit
windowrulev = idleinhibit fullscreen, class:.*

# xwayland related rules
windowrulev = noblur, xwayland:1, class:^(\bresolve\b)$

# Disabled by default (reference)
# windowrule = match:xwayland = 1, no_blur on
