# -----------------------------------------------------
# Environment Variables
# name: "Default"
# -----------------------------------------------------

# Default Settings in ml4w.conf
source = ~/.config/hypr/conf/environments/nvidia.conf
